include("Model_scripts/fig1acegi.jl")
include("Model_scripts/fig1bdfhj.jl")
include("Model_scripts/fig2acegi.jl")
include("Model_scripts/fig2bdfhj.jl")
include("Model_scripts/fig3acegi.jl")
include("Model_scripts/fig3bdfhj.jl")
